# Generated by Django 5.2.2 on 2025-10-31 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('company_approved', 'Компания одобрена'), ('company_rejected', 'Компания отклонена'), ('company_updated', 'Компания обновлена'), ('backup_created', 'Создан бэкап'), ('backup_restored', 'Бэкап восстановлен'), ('backup_deleted', 'Бэкап удален'), ('backup_downloaded', 'Бэкап скачан'), ('backup_uploaded', 'Бэкап загружен'), ('logs_cleared', 'Логи очищены')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
            options={
                'verbose_name': 'Лог администратора',
                'verbose_name_plural': 'Логи администраторов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название бэкапа')),
                ('backup_file', models.FileField(upload_to='backups/%Y/%m/%d/', verbose_name='Файл бэкапа')),
                ('backup_type', models.CharField(choices=[('full', 'Полный бэкап'), ('database', 'Только база данных'), ('media', 'Только медиафайлы')], default='database', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Бэкап',
                'verbose_name_plural': 'Бэкапы',
                'ordering': ['-created_at'],
            },
        ),
    ]
